name: Create Tag and Release
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_release_version.outputs.version }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Release Version
        id: get_release_version
        run: |
          echo "PR Merged, getting branch name"
          version=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oP '\d+\.\d+\.\d+')
          echo "Release version: $version"
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: Datom-lab/action-create-release@v0
        with:
          version: ${{ steps.get_release_version.outputs.version }}
          pr_body: ${{ github.event.pull_request.body }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  build_and_push_image:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Print version
        run: echo "Creating image for version ${{needs.create_release.outputs.version}}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jmpulo/fastapi-template:${{ needs.create_release.outputs.version }},jmpulo/fastapi-template:latest